-- MySQL Script generated by MySQL Workbench
-- Fri Nov  8 13:07:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ShoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShoppingCart` (
  `CartID` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `CreatedDate` DATETIME NULL,
  `Quantity` INT(20) NULL,
  PRIMARY KEY (`CartID`),
  UNIQUE INDEX `CardID_UNIQUE` (`CartID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `UserID` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `StatusID` INT UNSIGNED NOT NULL,
  `Username` VARCHAR(320) NOT NULL,
  `Password` VARCHAR(20) NOT NULL,
  `CreatedDate` DATETIME NOT NULL,
  `Email` VARCHAR(20) NULL,
  `ShoppingCart_CartID` INT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`UserID`, `ShoppingCart_CartID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE,
  INDEX `fk_User_ShoppingCart1_idx` (`ShoppingCart_CartID` ASC) VISIBLE,
  CONSTRAINT `fk_User_ShoppingCart1`
    FOREIGN KEY (`ShoppingCart_CartID`)
    REFERENCES `mydb`.`ShoppingCart` (`CartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seller` (
  `userID` INT(20) UNSIGNED NOT NULL,
  `User_UserID` INT(20) UNSIGNED NOT NULL,
  `User_StatusID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`userID`),
  INDEX `fk_Seller_User1_idx` (`User_UserID` ASC, `User_StatusID` ASC) VISIBLE,
  CONSTRAINT `fk_Seller_User1`
    FOREIGN KEY (`User_UserID` , `User_StatusID`)
    REFERENCES `mydb`.`User` (`UserID` , `StatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rating` (
  `RatingID` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `RatingValue` INT(3) UNSIGNED NOT NULL,
  `ReviewText` TEXT NOT NULL,
  `CreatedDate` DATETIME NOT NULL,
  PRIMARY KEY (`RatingID`),
  UNIQUE INDEX `RatingID_UNIQUE` (`RatingID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Auction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Auction` (
  `AuctionID` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `StartingPrice` INT(10) UNSIGNED NOT NULL,
  `Category` VARCHAR(5) NOT NULL,
  `ReservePrice` INT(10) UNSIGNED NOT NULL,
  `ImageURL` VARCHAR(25) NOT NULL,
  `StartDate` DATETIME NOT NULL,
  `EndDate` DATETIME NOT NULL,
  `Seller_SellerID` INT(20) UNSIGNED NOT NULL,
  `Rating_RatingID` INT(20) UNSIGNED NOT NULL,
  `Buyer_UserID` VARCHAR(20) NOT NULL,
  `Buyer_Bid_BidID` INT UNSIGNED NOT NULL,
  `Buyer_Bid_Buyer_BuyerID` INT(20) UNSIGNED NOT NULL,
  `highest bid` INT(20) NULL,
  `winner` VARCHAR(20) NULL,
  PRIMARY KEY (`AuctionID`, `Seller_SellerID`, `Rating_RatingID`, `Buyer_UserID`, `Buyer_Bid_BidID`, `Buyer_Bid_Buyer_BuyerID`),
  UNIQUE INDEX `AuctionID_UNIQUE` (`AuctionID` ASC) VISIBLE,
  INDEX `fk_Auction_Seller1_idx` (`Seller_SellerID` ASC) VISIBLE,
  INDEX `fk_Auction_Rating1_idx` (`Rating_RatingID` ASC) VISIBLE,
  CONSTRAINT `fk_Auction_Seller1`
    FOREIGN KEY (`Seller_SellerID`)
    REFERENCES `mydb`.`Seller` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auction_Rating1`
    FOREIGN KEY (`Rating_RatingID`)
    REFERENCES `mydb`.`Rating` (`RatingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Question` (
  `QuestionID` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `QuestionText` TEXT NOT NULL,
  `CreatedDate` DATETIME NOT NULL,
  `AuctionID` INT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`QuestionID`, `AuctionID`),
  UNIQUE INDEX `QuestionID_UNIQUE` (`QuestionID` ASC) VISIBLE,
  INDEX `fk_Question_Auction1_idx` (`AuctionID` ASC) VISIBLE,
  CONSTRAINT `fk_Question_Auction1`
    FOREIGN KEY (`AuctionID`)
    REFERENCES `mydb`.`Auction` (`AuctionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Answer` (
  `AnswerID` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `AnswerText` TEXT NOT NULL,
  `CreatedDate` DATETIME NOT NULL,
  `QuestionID` INT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`AnswerID`, `QuestionID`),
  INDEX `fk_Answer_Question1_idx` (`QuestionID` ASC) VISIBLE,
  CONSTRAINT `fk_Answer_Question1`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `mydb`.`Question` (`QuestionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bid` (
  `BidID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `BidAmount` INT NOT NULL,
  `BidTime` DATETIME NOT NULL,
  `Buyer_BuyerID` INT(20) UNSIGNED NOT NULL,
  `Auction_AuctionID` INT(20) UNSIGNED NOT NULL,
  `Auction_Seller_SellerID` INT(20) UNSIGNED NOT NULL,
  `Auction_Rating_RatingID` INT(20) UNSIGNED NOT NULL,
  `Auction_Buyer_UserID` VARCHAR(20) NOT NULL,
  `Auction_Buyer_Bid_BidID` INT UNSIGNED NOT NULL,
  `Auction_Buyer_Bid_Buyer_BuyerID` INT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`BidID`, `Buyer_BuyerID`, `Auction_AuctionID`, `Auction_Seller_SellerID`, `Auction_Rating_RatingID`, `Auction_Buyer_UserID`, `Auction_Buyer_Bid_BidID`, `Auction_Buyer_Bid_Buyer_BuyerID`),
  INDEX `fk_Bid_Auction1_idx` (`Auction_AuctionID` ASC, `Auction_Seller_SellerID` ASC, `Auction_Rating_RatingID` ASC, `Auction_Buyer_UserID` ASC, `Auction_Buyer_Bid_BidID` ASC, `Auction_Buyer_Bid_Buyer_BuyerID` ASC) VISIBLE,
  CONSTRAINT `fk_Bid_Auction1`
    FOREIGN KEY (`Auction_AuctionID` , `Auction_Seller_SellerID` , `Auction_Rating_RatingID` , `Auction_Buyer_UserID` , `Auction_Buyer_Bid_BidID` , `Auction_Buyer_Bid_Buyer_BuyerID`)
    REFERENCES `mydb`.`Auction` (`AuctionID` , `Seller_SellerID` , `Rating_RatingID` , `Buyer_UserID` , `Buyer_Bid_BidID` , `Buyer_Bid_Buyer_BuyerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Buyer` (
  `User_UserID` INT(20) UNSIGNED NOT NULL,
  `User_StatusID` INT UNSIGNED NOT NULL,
  `UserID` VARCHAR(20) NOT NULL,
  `Bid_BidID` INT UNSIGNED NOT NULL,
  `Bid_Buyer_BuyerID` INT(20) UNSIGNED NOT NULL,
  `Auction_AuctionID` INT(20) UNSIGNED NOT NULL,
  `Auction_Seller_SellerID` INT(20) UNSIGNED NOT NULL,
  `Auction_Rating_RatingID` INT(20) UNSIGNED NOT NULL,
  `Auction_Buyer_UserID` VARCHAR(20) NOT NULL,
  `Auction_Buyer_Bid_BidID` INT UNSIGNED NOT NULL,
  `Auction_Buyer_Bid_Buyer_BuyerID` INT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`UserID`, `Bid_BidID`, `Bid_Buyer_BuyerID`, `Auction_AuctionID`, `Auction_Seller_SellerID`, `Auction_Rating_RatingID`, `Auction_Buyer_UserID`, `Auction_Buyer_Bid_BidID`, `Auction_Buyer_Bid_Buyer_BuyerID`),
  INDEX `fk_Buyer_User1_idx` (`User_UserID` ASC, `User_StatusID` ASC) VISIBLE,
  INDEX `fk_Buyer_Bid1_idx` (`Bid_BidID` ASC, `Bid_Buyer_BuyerID` ASC) VISIBLE,
  INDEX `fk_Buyer_Auction1_idx` (`Auction_AuctionID` ASC, `Auction_Seller_SellerID` ASC, `Auction_Rating_RatingID` ASC, `Auction_Buyer_UserID` ASC, `Auction_Buyer_Bid_BidID` ASC, `Auction_Buyer_Bid_Buyer_BuyerID` ASC) VISIBLE,
  CONSTRAINT `fk_Buyer_User1`
    FOREIGN KEY (`User_UserID` , `User_StatusID`)
    REFERENCES `mydb`.`User` (`UserID` , `StatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Buyer_Bid1`
    FOREIGN KEY (`Bid_BidID` , `Bid_Buyer_BuyerID`)
    REFERENCES `mydb`.`Bid` (`BidID` , `Buyer_BuyerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Buyer_Auction1`
    FOREIGN KEY (`Auction_AuctionID` , `Auction_Seller_SellerID` , `Auction_Rating_RatingID` , `Auction_Buyer_UserID` , `Auction_Buyer_Bid_BidID` , `Auction_Buyer_Bid_Buyer_BuyerID`)
    REFERENCES `mydb`.`Auction` (`AuctionID` , `Seller_SellerID` , `Rating_RatingID` , `Buyer_UserID` , `Buyer_Bid_BidID` , `Buyer_Bid_Buyer_BuyerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
